### ISSUE TITLE
attachments query

### ISSUE THREAD

**Issue by godspeed20** [mailjet/mailjet-apiv3-php-simple#120]
Hi, so from the look of the api, if I want to add an attachment via sendEmail(), I just add something like this in the mail params: 
    "Attachments" => array(
        "nas.pdf" => "@/e:/ins/nas.pdf"
    )

But if i want to add an attachment via send() I have to add something like
 "Attachments" => json_decode('[{"Content-type":"text/plain","Filename":"test.txt","content":"VGhpcyBpcyB5b3VyIGF0dGFjaGVkIGZpbGUhISEK"}]', true)
);

I'm guessing under the hood sendEmail() is converting to base64 for me. is there a way to use the latter endpoint but without having encode the filename upfront? Bit like using the param format for sendEmail but with send() instead? Just wondering. thanks

**Comment by GuillaumeBadi** [comment]
Hey @godspeed20 !

What about that ?
``` php
function attachment($name, $path)
{
  $data = file_get_contents($path);
  $base64 = base64_encode($data);
  return array(
    'Filename' => $name,
    'Content-Type' => 'application/octet-stream',
    'content' => $base64
  );
}

$mj->send(array(
  'method' => 'POST',
  'FromEmail' => 'your sender email',
  'Recipients' => json_decode('[{"Email":"api@mailjet.com"}]', true),
  'Text-Part' => 'It worked!',
  'Attachments' => array(attachment('test.txt', 'Hello World'))
));
```

**Comment by GuillaumeBadi** [comment]
Hey @godspeed20 ! Please let me know if this function works for you ! I would be happy to follow up on that !

**Comment by godspeed20** [comment]
Hi, sorry for the delay, been a busy week. 

That does work better, I was struggling trying to construct a json string and then using jsondecode but your suggestion is a lot cleaner and much more stable. Thanks!

**Comment by GuillaumeBadi** [comment]
### Hey @godspeed20  :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!

**Comment by godspeed20** [comment]
Thanks Guillaume. To be honest I think we're not on 5.4 yet (work in progress), and we're still getting comfortable with the random response code 0's we seem to get, but once we move I'll definitely look into the new wrapper, thanks for the heads up!

**Comment by GuillaumeBadi** [comment]
"random response code 0's" ? could you be more specific about that. Maybe I can help on that :)

**Comment by godspeed20** [comment]
Unfortunately all I have is the error that comes back from $mail->response_code which is 0. I'm working on getting the body, if it looks api related I'll come back here and let you know, but suspect it's all central (like the 500's i get occasionally)

thanks

**Comment by kalps1993** [comment]
Hello Guys,

When i send mail with attachment in sendEmail() methode like below.

$params = array(
        "method" => "POST",
        "from" => "my@my.com",
        "to" => "email@email.com",
        "subject" => "Hello World!",
        "text" => "Greetings from ICAM.",
        "attachment" => array(
        	"first.txt"=>'@/E:\first.txt'
            )
    );

But it shown me error like below

Warning: file_get_contents(/E:\first.txt): failed to open stream: Invalid argument in C:\xampp\htdocs\mailjet\php-mailjet-v3-simple.class.php on line 139
success - email sent

Please provide me solution.
Thank in advance.

Thanks & Regards
Kalpesh Gohil
